# fly.toml - marcobroker daemon (cron-driven, não é HTTP server)
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'marcobrokernews'
primary_region = 'gru'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
